apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-etl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-etl
  template:
    metadata:
      labels:
        app: analytics-etl
    spec:
      containers:
      - name: analytics-etl
        image: analytics-etl:latest
        imagePullPolicy: Always
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: analytics-config
              key: environment
        envFrom:
        - secretRef:
            name: analytics-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
