# Development environment configuration
environment: dev

extends:
  - ../common/base_config.yaml

app:
  log_level: DEBUG

collectors:
  mongodb:
    uri: ${MONGODB_DEV_URI}
    database: analytics_dev
    
  newrelic:
    account_id: ${NEWRELIC_DEV_ACCOUNT_ID}
    api_key: ${NEWRELIC_DEV_API_KEY}
    
  postgres:
    host: ${POSTGRES_DEV_HOST}
    port: 5432
    database: analytics_dev
    user: ${POSTGRES_DEV_USER}
    password: ${POSTGRES_DEV_PASSWORD}

storage:
  warehouse_path: s3://analytics-warehouse/dev
  retention_days: 30

powerbi:
  workspace_id: ${POWERBI_DEV_WORKSPACE_ID}
  dataset_id: ${POWERBI_DEV_DATASET_ID}
  refresh_interval_hours: 4
