apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namePrefix: stage-

configMapGenerator:
  - name: analytics-config
    behavior: merge
    literals:
      - environment=stage
      - storage__warehouse_path=s3://analytics-warehouse/stage
